command:
  - streamlit
  - run
  - app.py
  - --server.port
  - "8000"
  - --server.headless
  - "true"

env:
  - name: CHATBOT_API_URL
    value: "https://chatbot-api-7474647357732356.aws.databricksapps.com"
  - name: AZURE_OPENAI_ENDPOINT
    value: "https://genaimarketplace-api.kenvue.com/"
  - name: AZURE_OPENAI_API_KEY
    valueFrom: 42078e30-106d-43da-bef9-fc1152ce418c
  - name: AZURE_OPENAI_API_VERSION
    value: "2025-01-01-preview"
